### ISSUE TITLE
Issue with make

### ISSUE THREAD

**Issue by Stenberggg** [stadie/btt_tft35spi_rpi#1]
First of all, thank you so much for your work.

I think I am able to find my way around with SSH on RBpi, but I'm new to Github other than grabbing repos and I have very limited coding experience, so please have some patience with my error-reporting. I'm prepared to put in the work to make it as easy as possible for you to help me if you can. If you want any logs etc, please say so and I will try my best to oblige.

I'm on a RBpi5, pios lite and Klipper/Mainsail built with KIAUH. I've gotten the TFT35 SPI working with klipperscreen before I stumbled upon your repo. I'm able to follow the instructions down to cloning your repository and running make, which after saving the files; "tsc2007_core.c" and "tsc2007.h" throws this error:

`make -C /lib/modules/6.1.0-rpi7-rpi-v8/build M=/home/Simen/btt_tft35/tsc2007 modules
make[1]: *** /lib/modules/6.1.0-rpi7-rpi-v8/build: No such file or directory.  Stop.
make: *** [Makefile:16: module] Error 2`

Can this be because I just installed kernel headers and not the kernel source? I verified that there was no folder in /lib/modules/6.1.0-rpi7-rpi-v8 named "build".

I created the missing folder and ran make again, which then resulted in this error:
`Simen@Pi5:~/btt_tft35/tsc2007 $ make
make -C /lib/modules/6.1.0-rpi7-rpi-v8/build M=/home/Simen/btt_tft35/tsc2007 modules
make[1]: Entering directory '/usr/lib/modules/6.1.0-rpi7-rpi-v8/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/6.1.0-rpi7-rpi-v8/build'
make: *** [Makefile:16: module] Error 2`

**Comment by stadie** [comment]
Hi,

I am excited that someone else tried this. Unfortunately, I did no extensive testing of the setup and wanted to wait for my next build to try the instructions on a freshly installed rpi. 
You are right the "build" directory might not come from the kernel-headers, but "rpi-source" that I have also run in  my tries. 

Please try to install and run rpi-source from https://github.com/RPi-Distro/rpi-source:
You run in your home directory:
sudo wget https://raw.githubusercontent.com/RPi-Distro/rpi-source/master/rpi-source -O /usr/local/bin/rpi-source && sudo chmod +x /usr/local/bin/rpi-source && /usr/local/bin/rpi-source -q --tag-update
and
rpi-source

When this fixes the problem I will update the git page. 

Cheers!

**Comment by stadie** [comment]
PS. Delete the "build" directory that you have created by hand first.

**Comment by Stenberggg** [comment]
Thank you for the swift response. Seems my luck has run dry as there's no source for my kernel on the RBpi5?

```
Simen@Pi5:~ $ rpi-source --processor 1

 *** SoC: BCM2836
ERROR:
Can't find a source for this kernel

Help: https://github.com/RPi-Distro/rpi-source/blob/master/README.md
```

**Comment by stadie** [comment]
Hm, too bad. I fear that rpi-source does not support an rpi5 yet.

There are now "official" rpi kernel headers:
sudo apt install linux-headers-rpi-v8
However, I do not know which directories they will populate.

If I find time I will try  them on a freshly installed pi zero 2  in the coming days.

**Comment by Stenberggg** [comment]
`Simen@Pi5:~ $ sudo apt install linux-headers-rpi-v8
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 linux-headers-6.1.0-rpi7-rpi-v8:arm64 : Depends: gcc-12:arm64 but it is not installable
E: Unable to correct problems, you have held broken packages.`

**Comment by stadie** [comment]
Ok, I have tried it on a rpi zero 2 with rpi OS bookworm lite 64bit without any additional packages installed.
It worked for me with the linux-headers-rpi-v8 and I have updated the ReadMe accordingly.
My system was: uname -a
Linux micron 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

I am not sure what is missing for rpi 5 to get a build system. On my system the headers were even installed already.

**Comment by stadie** [comment]
I installed [https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2023-12-11/2023-12-11-raspios-bookworm-arm64-lite.img.xz](https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2023-12-11/2023-12-11-raspios-bookworm-arm64-lite.img.xz) with rpi imager which is newer than the version installed by default by rpi imager.
Did you run
sudo apt-get update
sudo apt-get upgrade
after the  first boot?

**Comment by Stenberggg** [comment]
I'm just finished with backing up all settings and custom tools to the point that I'm confident I can recreate it on a fresh install if I have missed anything. I'll just start clean to weed out any mistakes I have possibly made previously and report back

**Comment by Stenberggg** [comment]
I'm very happy to confirm that on a clean x64 install, I had the kernel headers installed aswell on RBpi5. I now have a working touch screen running off SPI1-2 with dc-pin=26 and SDA on gpio 2, SCL on gpio3.

I would like to apologize since the error had to have been between my keyboard and chair and not your code. Then I would like to thank you so much for your patience and help with getting this to run. Ive designed and printed some brackets that perfectly centers this screen in the default mounting location on ender 3-style printers and this repository is the cherry on top in making this a really clean Klipperscreen replacement for the stock 12864. Thank you for your awesome work!

**Comment by stadie** [comment]
Nice, I am glad that it worked in the end. Thanks for being my first tester!
