### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by mariusdp** [stadie/btt_tft35spi_rpi#2]
Hi and thanks for the great work 👍 

When I try to 'make' I get an error and can not figure why. Can you please help. below is the output:

pi@raspberrypi:~/btt_tft35/tsc2007 $ make
make -C /lib/modules/6.6.28+rpt-rpi-v8/build M=/home/pi/btt_tft35/tsc2007 modules
make[1]: Entering directory '/usr/src/linux-headers-6.6.28+rpt-rpi-v8'
  CC [M]  /home/pi/btt_tft35/tsc2007/tsc2007_core.o
/home/pi/btt_tft35/tsc2007/tsc2007_core.c: In function ‘tsc2007_calculate_resistance’:
/home/pi/btt_tft35/tsc2007/tsc2007_core.c:73:9: warning: unused variable ‘rt’ [-Wunused-variable]
   73 |     u32 rt = 0;
      |         ^~
/home/pi/btt_tft35/tsc2007/tsc2007_core.c: At top level:
/home/pi/btt_tft35/tsc2007/tsc2007_core.c:531:27: error: initialization of ‘int (*)(struct i2c_client *)’ from incompatible pointer type ‘int (*)(struct i2c_client *, const struct i2c_device_id *)’ [-Werror=incompatible-pointer-types]
  531 |         .probe          = tsc2007_probe,
      |                           ^~~~~~~~~~~~~
/home/pi/btt_tft35/tsc2007/tsc2007_core.c:531:27: note: (near initialization for ‘tsc2007_driver.probe’)
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-6.6.28+rpt-common-rpi/scripts/Makefile.build:248: /home/pi/btt_tft35/tsc2007/tsc2007_core.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.6.28+rpt-common-rpi/Makefile:1938: /home/pi/btt_tft35/tsc2007] Error 2
make[1]: *** [/usr/src/linux-headers-6.6.28+rpt-common-rpi/Makefile:246: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.6.28+rpt-rpi-v8'
make: *** [Makefile:16: module] Error 2

**Comment by drzoidberger** [comment]
Hi, which linux release are you using? Kernel 6.6 might not be compatible with the tsc2007 driver from btt and the underlying interface might have changed between kernel 6.1 and 6.6.

**Comment by stadie** [comment]
Hi, can you update your local repository and try again? For me it compiles now on bookworm and the code changes should not affect the module itself.

**Comment by mariusdp** [comment]
> Hi, can you update your local repository and try again? For me it compiles now on bookworm and the code changes should not affect the module itself.

Still not working. Will try a fresh install later on The error I get now from dsmeg (was the same before update) is:

[    4.265081] tsc2007 22-0048: Pen down GPIO is not specified in properties
[    4.265161] tsc2007 22-0048: Failed to request irq 0: -22
[    4.265193] tsc2007: probe of 22-0048 failed with error -22

**Comment by mariusdp** [comment]
using a Manta E3EZ if of any importance. Connected to small zif port (SPI) with the ribbon. The pinout is:
GPIO 9 - MISO
GPIO 10 - MOSI
GPIO 11 - SCK
GPIO 4 - LCD_CS
GPIO 17 - TOUCH_CS
GPIO 27 - SDA
GPIO 22 - SCL

**Comment by stadie** [comment]
Ah, ok. At least the module got compiled and could be loaded. The "Pen down GPIO is not specified in properties" message looks like something has changed in the arguments for the module. I will have a look with a test setup.

**Comment by stadie** [comment]
So you use a manta 3ez with a CM4?

**Comment by stadie** [comment]
Did you do the "make install"? It looks like there is the default tsc2007.ko driver on the system that might confuse things.
What do get from: 
```ls -l /lib/modules/`uname -r`/kernel/drivers/input/touchscreen```

**Comment by mariusdp** [comment]
> So you use a manta 3ez with a CM4?

Yes. And EBB42 CAN. All works so far except touch - that is why so thrilled when I found this.

ls -l /lib/modules/`uname -r`/kernel/drivers/input/touchscreen --> I'll get back on this later in the evening when I'll get home.

Thank you for looking into this...

**Comment by mariusdp** [comment]
> ls -l /lib/modules/`uname -r`/kernel/drivers/input/touchscreen

It does load another one. tsc2007.ko.xy was already there before installing this driver - started with clean setup t confirm...
pi@raspberrypi:~ $ ls -l /lib/modules/`uname -r`/kernel/drivers/input/touchscreen
total 112
-rw-r--r-- 1 root root  7392 Apr 22 14:49 ads7846.ko.xz
-rw-r--r-- 1 root root  9316 Apr 22 14:49 edt-ft5x06.ko.xz
-rw-r--r-- 1 root root  2556 Apr 22 14:49 egalax_ts.ko.xz
-rw-r--r-- 1 root root  4180 Apr 22 14:49 exc3000.ko.xz
-rw-r--r-- 1 root root  9244 Apr 22 14:49 goodix_ts.ko.xz
-rw-r--r-- 1 root root  7112 Apr 22 14:49 ili210x.ko.xz
-rw-r--r-- 1 root root  6220 Apr 22 14:49 iqs5xx.ko.xz
-rw-r--r-- 1 root root  2980 Apr 22 14:49 raspberrypi-ts.ko.xz
-rw-r--r-- 1 root root  3400 Apr 22 14:49 stmpe-ts.ko.xz
-rw-r--r-- 1 root root 24656 Apr 27 21:25 tsc2007.ko
-rw-r--r-- 1 root root  4604 Apr 22 14:49 tsc2007.ko.xz
-rw-r--r-- 1 root root  8156 Apr 22 14:49 usbtouchscreen.ko.xz

**Comment by stadie** [comment]
Thanks! I am currently fighting to get the display show the klipperscreen on bookworm, so that I can test the touch.

**Comment by mariusdp** [comment]
Display worked out of the box with the CM4 config.txt changes. Installed using kiauh (klipper, moonraker, mainsail and finaly klipperscreen).

**Comment by stadie** [comment]
Hi, the last times I had also no problems which makes it very annoying. 

The overlay for the touch was missing the resistance for y.  I have added it and pushed the change. 
I have no idea why this was not a problem before.
```
git pull
make all install
```
in the tsc2007 folder should get the fix.
With this I get in dmesg:
```
[    9.393607] tsc2007: loading out-of-tree module taints kernel.
[    9.394544] tsc2007 11-0048: Pen down GPIO is not specified in properties
[    9.395396] input: TSC2007 Touchscreen as /devices/platform/ffffffff.i2c/i2c-11/11-0048/input/input0

```
When I cat the input device I see output when I press on the dispay:
```
pi@micron:~ $  cat /dev/input/by-path/platform-ffffffff.i2c-event 
??.f)?J??.f)????.f)???.f)????.f)???.fhi??.fh??.fh?
??.f???.??.f3'  

```
This looks promising...
Can you give it a try?

**Comment by mariusdp** [comment]
It works. Had to delete tsc2007.ko.xz and rename the generated one but work fine now. Thank you.

On a separate note: after adding 'fbcon=map:10 fbcon=font:8x8 logo.nologo' to cmdline reboot halts with 'watchdog: watchdog0: watchdog did not stop!'

Any idea how to fix that??

**Comment by stadie** [comment]
Great!

I also get the annoying "watchdog" messages. There should be a newer display driver available  in the kernel, I will try to use it and see if it removes the problem.

**Comment by stadie** [comment]
Hi, I think the watchdog messages are harmless and for me everything looks fine with bookworm. Hence, I am closing this issue.
