### ISSUE TITLE
CM4 / Manta M5P / Bookworm: Touch not working due to IRQ issue

### ISSUE THREAD

**Issue by bullitt186** [stadie/btt_tft35spi_rpi#3]
Thank you for the great writeup on how to get the TFT35 working.

Here's the configuration i am using:

BTT Manta M5P
Raspberry Pi CM4 EMMC
Raspberry Pi OS Lite Bookworm 64 Bit (#1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25))
BTT TFT35 connected via SPI Connector on the bottom of the Manta Board

The screen works and after uncommenting `dtoverlay=vc4-kms-v3d` in config.txt, also KlipperScreen shows up.

However for touch I followed your instructions and these config.txt paramers

```
dtoverlay=i2c-gpio,i2c_gpio_sda=27,i2c_gpio_scl=22,i2c_gpio_delay_us=3
dtoverlay=tft_touch
```
Unfortunately apparently tsc2007 does not get an IRQ:
```
dmesg | grep "tsc2007"
[    4.736891] tsc2007 22-0048: Pen down GPIO is not specified in properties
[    4.736924] tsc2007 22-0048: Failed to request irq 0: -22
[    4.736936] tsc2007: probe of 22-0048 failed with error -22 
```

Could you guide me / give me hints how to change the IRQ or get touch up and running?

Thank you very much,
bullitt168

**Comment by drzoidberger** [comment]
Hi, I cannot remember seeing this problem with my setups lately. 
I will upgrade my pi to the same kernel version to check if this might trigger the interrupt error.

**Comment by drzoidberger** [comment]
Hi, I got the same error after the kernel update.
It went away after rebuilding and reinstalling the module:
cd btt_tft35
cd tsc2007
make clean
make
make install
sudo reboot

I hope this helps in your case as well...

Cheers,
Hartmut

**Comment by bullitt186** [comment]
Thank you for the prompt analysis and solution.
in fact the simple rebuild and reinstall fixed the issue for me as well.  So thanks a lot!!

Oddly, i did the initial install and the re-install on a freshly set up CM4 without a kernel upgrade or any other updates inbetween.
I also still get these messages but touch works as expected now.
```
dmesg | grep "tsc2007"
[    4.720688] tsc2007: loading out-of-tree module taints kernel.
[    4.721213] tsc2007 22-0048: Pen down GPIO is not specified in properties
```
Furthermore my system is not rebooting, stopping the reboot process with "watchdog0: watchdog did not stop!"
But i guess this is totally unrelated.

So thanks once again!

**Comment by drzoidberger** [comment]
Hi,

great. I am also getting the kernel messages. I think that the "pen down" message stems from the fact that  the original driver/hardware supports more options/pins than the BTT version. 
The "watchdog" is indeed annoying but I think unrelated.

Cheers!
